name: "multi_db_postgres"

services:
  db:
    image: "postgres:latest"
    container_name: "postgres"
    restart: unless-stopped
    volumes:
      - ./tools/postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_MULTIPLE_DATABASES=db1,db2,db3
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres